/// Flutter icons StoodeeIcons
/// Copyright (C) 2024 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  StoodeeIcons
///      fonts:
///       - asset: fonts/StoodeeIcons.ttf
///
///
/// * Entypo, Copyright (C) 2012 by Daniel Bruce
///         Author:    Daniel Bruce
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.entypo.com
/// * Font Awesome 4, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
/// * Font Awesome 5, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL (https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt)
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
library;

import 'package:flutter/widgets.dart';

class StoodeeIcons {
  StoodeeIcons._();

  static const _kFontFam = 'StoodeeIcons';
  static const String? _kFontPkg = null;

  static const IconData home =
      IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user =
      IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData trophy =
      IconData(0xf091, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tasks =
      IconData(0xf0ae, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData flashcards =
      IconData(0xf24d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
